### ISSUE TITLE
V2.1 - Sensors not created

### ISSUE THREAD

**Issue by grantclem** [amaximus/garbage-collection-card#9]
Latest update in HACS - Lost garbage sensors
Setup through Integrations

```
2019-11-03 08:30:22 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Waste for garbage_collection
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config_entries.py", line 190, in async_setup
    hass, self
  File "/home/homeassistant/.homeassistant/custom_components/garbage_collection/__init__.py", line 75, in async_setup_entry
    CC_STARTUP_VERSION.format(name=DOMAIN, version=VERSION, issue_link=ISSUE_URL)
NameError: name 'CC_STARTUP_VERSION' is not defined
2019-11-03 08:30:22 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Recycle for garbage_collection
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config_entries.py", line 190, in async_setup
    hass, self
  File "/home/homeassistant/.homeassistant/custom_components/garbage_collection/__init__.py", line 75, in async_setup_entry
    CC_STARTUP_VERSION.format(name=DOMAIN, version=VERSION, issue_link=ISSUE_URL)
NameError: name 'CC_STARTUP_VERSION' is not defined
2019-11-03 08:30:22 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Green Waste for garbage_collection
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config_entries.py", line 190, in async_setup
    hass, self
  File "/home/homeassistant/.homeassistant/custom_components/garbage_collection/__init__.py", line 75, in async_setup_entry
    CC_STARTUP_VERSION.format(name=DOMAIN, version=VERSION, issue_link=ISSUE_URL)
NameError: name 'CC_STARTUP_VERSION' is not defined


```

**Comment by amaximus** [comment]
Please note that you have issues with the garbage_collection custom component, not the custom Lovelace card that makes use of the sensors and its attributes of the custom component.
Long story short, you reported your issue to wrong place.

**Comment by grm** [comment]
Sorry, I made a mistake and created another issue instead.
